import argparse

parser = argparse.ArgumentParser(description='VadCLIP')
parser.add_argument('--seed', default=234, type=int)
parser.add_argument('--data-order-seed', default=None, type=int)

parser.add_argument('--embed-dim', default=512, type=int)
parser.add_argument('--visual-length', default=256, type=int)
parser.add_argument('--visual-width', default=512, type=int)
parser.add_argument('--visual-head', default=1, type=int)
parser.add_argument('--visual-layers', default=1, type=int)
parser.add_argument('--attn-window', default=64, type=int)
parser.add_argument('--prompt-prefix', default=10, type=int)
parser.add_argument('--prompt-postfix', default=10, type=int)
parser.add_argument('--classes-num', default=7, type=int)

parser.add_argument('--max-epoch', default=10, type=int)
parser.add_argument('--model-path', default='model/model_xd.pth')
parser.add_argument('--use-checkpoint', default=False, type=bool)
parser.add_argument('--checkpoint-path', default='model/checkpoint.pth')
parser.add_argument('--warm-start-path', default=None)
parser.add_argument('--output-dir', default=None)
parser.add_argument('--current-model-path', default='model/model_cur.pth')
parser.add_argument('--metrics-path', default=None)
parser.add_argument('--eval-every-steps', default=0, type=int)
parser.add_argument('--eval-at-epoch-end', action='store_true')
parser.add_argument('--selection-metric', default='text_ap')
parser.add_argument('--batch-size', default=96, type=int)
parser.add_argument('--train-list', default='list/xd_CLIP_rgb.csv')
parser.add_argument('--test-list', default='list/xd_CLIP_rgbtest.csv')
parser.add_argument('--gt-path', default='list/gt.npy')
parser.add_argument('--gt-segment-path', default='list/gt_segment.npy')
parser.add_argument('--gt-label-path', default='list/gt_label.npy')

parser.add_argument('--lr', default=1e-5)
parser.add_argument('--scheduler-rate', default=0.1)
parser.add_argument('--scheduler-milestones', default=[3, 6, 10])

parser.add_argument('--tracepoint', action='store_true')
parser.add_argument('--tracepoint-duration-bins', nargs='+', type=int, default=[1, 2, 4, 8, 16, 32, 64])
parser.add_argument('--tracepoint-hidden-dim', default=0, type=int)
parser.add_argument('--tracepoint-no-history', action='store_false', dest='tracepoint_use_history')
parser.add_argument('--tracepoint-hurdle-gate', action='store_true')
parser.add_argument('--tracepoint-global-hurdle-only', action='store_true')
parser.add_argument('--tracepoint-detach-mark-features', action='store_true', default=True)
parser.add_argument('--tracepoint-init-seed', default=100237, type=int)
parser.add_argument('--tracepoint-freeze-backbone', action='store_true')
parser.add_argument('--tracepoint-no-save-checkpoint', action='store_false', dest='tracepoint_save_checkpoint')
parser.add_argument('--tracepoint-save-optimizer', action='store_true')
parser.add_argument('--tracepoint-lr', default=None, type=float)
parser.add_argument('--tracepoint-hurdle-weight', default=1.0, type=float)
parser.add_argument('--tracepoint-normal-zero-weight', default=0.0, type=float)
parser.add_argument('--tracepoint-gate-only-zero-loss', action='store_true')
parser.add_argument('--tracepoint-no-fusion', action='store_false', dest='tracepoint_fuse', default=False)
parser.add_argument('--tracepoint-fuse', action='store_true', dest='tracepoint_fuse', help=argparse.SUPPRESS)
parser.add_argument('--tracepoint-warmup-epochs', default=0, type=int)
parser.add_argument('--tracepoint-fusion-mil-weight', default=0.0, type=float)
parser.add_argument('--tracepoint-count-cap', default=2.0, type=float)
parser.add_argument('--tracepoint-count-weight', default=0.05, type=float)
parser.add_argument('--tracepoint-duration-weight', default=0.01, type=float)
parser.add_argument('--tracepoint-fragment-weight', default=0.01, type=float)
parser.add_argument('--tracepoint-align-weight', default=0.0, type=float)
